package dev.lotr.app.theme

import androidx.compose.ui.graphics.Color

// region Light
val LightPrimary = Color(0xFF006c54)
val LightOnPrimary = Color(0xFFffffff)
val LightPrimaryContainer = Color(0xFF7ef8d3)
val LightOnPrimaryContainer = Color(0xFF012018)
val LightSecondary = Color(0xFF4b635a)
val LightOnSecondary = Color(0xFFffffff)
val LightSecondaryContainer = Color(0xFFcee9dd)
val LightOnSecondaryContainer = Color(0xFF072019)
val LightTertiary = Color(0xFF416376)
val LightOnTertiary = Color(0xFFffffff)
val LightTertiaryContainer = Color(0xFFc4e8ff)
val LightOnTertiaryContainer = Color(0xFF001e2c)
val LightError = Color(0xFFba1b1b)
val LightErrorContainer = Color(0xFFffdad4)
val LightOnError = Color(0xFFffffff)
val LightOnErrorContainer = Color(0xFF410001)
val LightBackground = Color(0xFFfbfdfa)
val LightOnBackground = Color(0xFF191c1b)
val LightSurface = Color(0xFFfbfdfa)
val LightOnSurface = Color(0xFF191c1b)
val LightSurfaceVariant = Color(0xFFdbe5df)
val LightOnSurfaceVariant = Color(0xFF3f4945)
val LightOutline = Color(0xFF6f7974)
val LightInverseOnSurface = Color(0xFFeff1ee)
val LightInverseSurface = Color(0xFF2d312f)
// endregion

// region Dark
val DarkPrimary = Color(0xFF61dbb8)
val DarkOnPrimary = Color(0xFF00382a)
val DarkPrimaryContainer = Color(0xFF00513f)
val DarkOnPrimaryContainer = Color(0xFF7ef8d3)
val DarkSecondary = Color(0xFFb2ccc1)
val DarkOnSecondary = Color(0xFF1d352d)
val DarkSecondaryContainer = Color(0xFF344b43)
val DarkOnSecondaryContainer = Color(0xFFcee9dd)
val DarkTertiary = Color(0xFFa8cbe2)
val DarkOnTertiary = Color(0xFF0d3446)
val DarkTertiaryContainer = Color(0xFF284b5e)
val DarkOnTertiaryContainer = Color(0xFFc4e8ff)
val DarkError = Color(0xFFffb4a9)
val DarkErrorContainer = Color(0xFF930006)
val DarkOnError = Color(0xFF680003)
val DarkOnErrorContainer = Color(0xFFffdad4)
val DarkBackground = Color(0xFF191c1b)
val DarkOnBackground = Color(0xFFe1e3e0)
val DarkSurface = Color(0xFF191c1b)
val DarkOnSurface = Color(0xFFe1e3e0)
val DarkSurfaceVariant = Color(0xFF3f4945)
val DarkOnSurfaceVariant = Color(0xFFbfc9c3)
val DarkOutline = Color(0xFF89938e)
val DarkInverseOnSurface = Color(0xFF191c1b)
val DarkInverseSurface = Color(0xFFe1e3e0)
// endregion
